# Generated by Django 5.0.7 on 2024-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="job_title",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
