# Generated by Django 5.0.7 on 2024-08-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_contact_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="invoice_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_contact",
                to="clients.contact",
            ),
        ),
    ]
