# Generated by Django 5.0.7 on 2024-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_invoice_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
