# Generated by Django 5.0.7 on 2024-08-06 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_technician"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketupdate",
            name="tech_first_name",
        ),
        migrations.RemoveField(
            model_name="ticketupdate",
            name="tech_last_name",
        ),
        migrations.AddField(
            model_name="ticketupdate",
            name="tech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_tech",
                to="support.technician",
            ),
        ),
    ]
