# Generated by Django 5.0.7 on 2024-08-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_remove_ticketupdate_tech_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="is_resolved",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolved_ticket",
                to="support.ticketupdate",
            ),
        ),
    ]
