# Generated by Django 5.0.7 on 2024-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_alter_ticket_is_resolved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketupdate",
            name="is_resolved",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
